[project]
name = "llms_kgs"
version = "0.0.1"
authors = [
  { name="Matías Torres Esteban", email="mat.torreta@gmail.com" },
]
description = "Paquete que permite trabajar con los Grandes Modelos de Lenguaje (LLM, por sus siglas en inglés) y los Grafos de Conocimiento (KG, por sus siglas en inglés)"
readme = "README.md"
requires-python = ">=3.9"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
license = "MIT"
license-files = ["LICEN[CS]E*"]
[tool.setuptools.packages.find]
where = ["src"]
